#!/usr/bin/env python3
"""
Loom's mark: three warp threads (light) and three weft threads (white),
woven over and under, the way a loom turns loose threads into cloth, and
Loom turns scattered files into one ordered place.

Writes the SVG sources in brand/ (and Android's vector drawables when
given a res/ folder). brand/build.sh renders every PNG and ICO from these.
"""
import sys
from pathlib import Path

BLUE = "#1A5FF0"
WARP = "#B5CBFF"
WEFT = "#FFFFFF"

# Geometry on a 1024 grid: thread centres 230 apart, threads 136 wide,
# 24-unit gaps where one thread passes under another.
PITCH, WIDTH, GAP, END_R = 230, 136, 24, 12


def rects(scale=1.0, cx=512.0, cy=512.0):
    """The mark as separate thread pieces: (x, y, w, h, rx, "warp"|"weft").

    Where a thread passes under another it is cut, leaving a gap on both
    sides of the thread on top, so the pieces never overlap and the mark
    works on any background, in colour or in a single colour.
    """
    p, w, g, er = PITCH * scale, WIDTH * scale, GAP * scale, END_R * scale
    cs = [-p, 0.0, p]
    lo, hi = -p - w / 2, p + w / 2
    out = []
    for k, kind in ((0, "weft"), (1, "warp")):
        for j, c in enumerate(cs):
            # Where this thread goes under: at crossings where the other one is on top.
            unders = [o for i, o in enumerate(cs) if ((i + j) % 2 == 1) == (kind == "warp")]
            start = lo
            for o in unders + [None]:
                stop = hi if o is None else o - w / 2 - g
                if stop > start:
                    if kind == "weft":
                        out.append((cx + start, cy + c - w / 2, stop - start, w, er, kind))
                    else:
                        out.append((cx + c - w / 2, cy + start, w, stop - start, er, kind))
                if o is not None:
                    start = o + w / 2 + g
    return out


def svg(tile_rx=230, scale=1.0, tile=True, colours=None):
    c = {"warp": WARP, "weft": WEFT, **(colours or {})}
    body = "".join(
        f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}"{f" rx={chr(34)}{r:g}{chr(34)}" if r else ""} fill="{c[k]}"/>'
        for x, y, w, h, r, k in rects(scale)
    )
    bg = f'<rect width="1024" height="1024" rx="{tile_rx}" fill="{BLUE}"/>' if tile else ""
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">{bg}{body}</svg>\n'


def android_vector(colours, scale):
    """An Android vector drawable (108 dp adaptive-icon layer) of the mark."""
    paths = []
    for x, y, w, h, _r, k in rects(scale):
        f = colours[k]
        s = 108 / 1024
        paths.append(
            f'    <path android:fillColor="{f}" android:pathData="M{x*s:.2f},{y*s:.2f}h{w*s:.2f}v{h*s:.2f}h{-w*s:.2f}z"/>'
        )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by brand/mark.py -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="108" android:viewportHeight="108">\n'
        + "\n".join(paths)
        + "\n</vector>\n"
    )


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    (here / "loom.svg").write_text(svg())                    # the app icon: rounded tile
    (here / "loom-square.svg").write_text(svg(tile_rx=0, scale=0.82))  # full-bleed (iOS/Android round it)
    (here / "loom-maskable.svg").write_text(svg(tile_rx=0, scale=0.62))  # inside the maskable safe zone
    (here / "loom-glyph.svg").write_text(svg(tile=False, colours={"warp": "#1A5FF0", "weft": "#1A5FF0"}))  # one colour, no tile
    if len(sys.argv) > 1:  # Android res/ folder
        res = Path(sys.argv[1])
        (res / "drawable").mkdir(parents=True, exist_ok=True)
        # The foreground sits inside the 66 dp safe circle of the 108 dp layer.
        (res / "drawable" / "ic_launcher_foreground.xml").write_text(
            android_vector({"warp": WARP, "weft": WEFT}, 0.5))
        # Themed (monochrome) icon: one colour; the launcher tints it. The gaps become holes.
        (res / "drawable" / "ic_launcher_monochrome.xml").write_text(
            android_vector({"warp": "#FFFFFFFF", "weft": "#FFFFFFFF"}, 0.5))
        (res / "drawable" / "ic_splash.xml").write_text(
            android_vector({"warp": WARP, "weft": WEFT}, 0.5))
        (res / "drawable" / "ic_notification.xml").write_text(
            android_vector({"warp": "#FFFFFFFF", "weft": "#FFFFFFFF"}, 0.78))
